/**
 * Generates a small, single-topic ("atomic"/topic-scoped) client per topic instead of one client
 * covering the whole service - contract-document.md §5.3. A consumer that calls only one topic gets a
 * client scoped to just that topic: its `RequiredTopics` array and its embedded contract hash cover
 * only that topic's contract, so an unrelated change elsewhere on the producing service neither drags
 * in unused surface nor invalidates this client. Port of `Benzene.CodeGen.Client.AtomicClientSdkBuilder`.
 *
 * Reuses `renderClientModule` (from `MessageClientSdkBuilder.ts`) against each topic's already-
 * projected, self-contained document (`projectTopicScoped` - one request, no events, only the
 * component schemas that request reaches), so the generated client/interface/DTO shapes match the
 * service-level client exactly and the contract hash falls out topic-scoped. Each topic is emitted
 * under its own client name (from `TopicMethodName` by default, e.g. `payments:capture` ->
 * `PaymentsCapture`), so one document yields one atomic client per topic.
 */
import { ClientSdkOptions } from './ClientSdkOptions';
import { ContractDocument } from './ContractDocument';
import { GeneratedClient, namespacedFileName, renderClientModule } from './MessageClientSdkBuilder';
import { toIdentifierSegment } from './NameFormatter';
import { IMethodName, TopicMethodName, TopicReversedMethodName } from './TopicMethodName';
import { applyTopicScope } from './TopicScope';
import { projectTopicScoped } from './TopicScopedDocument';

export interface AtomicClientSdkOptions extends ClientSdkOptions {
  /** Derives each topic's client name from its topic id (default `TopicMethodName`, e.g. `user:create` -> `UserCreate`). */
  clientName?: IMethodName;
  /** The topic -> method-base strategy used *inside* each atomic client (default `TopicReversedMethodName`). */
  methodName?: IMethodName;
}

/**
 * Generates one topic-scoped client per in-scope topic, plus - when `options.serviceName` is given and
 * at least one client was generated - one aggregate `add{ServiceName}Clients()` registration function
 * that calls every per-topic client's own registration in turn, so a consumer taking several topics off
 * the same service registers them in one line instead of N (mirrors C#'s
 * `AtomicClientSdkBuilder.BuildAggregateRegistration`). Without a `serviceName` there is nothing to
 * name the aggregate under, so it is simply not emitted - each per-topic client still carries its own
 * `add{ClientName}ServiceClient()`.
 */
export function buildAtomicClientSdk(
  document: ContractDocument,
  options: AtomicClientSdkOptions,
): readonly GeneratedClient[] {
  const scoped = applyTopicScope(document, options);
  const clientName = options.clientName ?? new TopicMethodName();
  const methodName = options.methodName ?? new TopicReversedMethodName();

  const clientNames: string[] = [];
  const files = scoped.requests.map((request): GeneratedClient => {
    const name = toIdentifierSegment(clientName.create(request.topic));
    clientNames.push(name);
    // projectTopicScoped narrows against the FULL document's catalogue, not the include-list-filtered
    // `scoped` one: the include-list only ever narrows which topics get a client, never which schemas
    // a given topic's own request/response reach.
    const topicDocument = projectTopicScoped(document, request.topic);
    return {
      fileName: namespacedFileName(options.namespace, `${name}/${name}ServiceClient.ts`),
      // contract-document.md §5.3's topic-scoped shape: its contract hash does not strip a reserved
      // entry entirely (only its flag) - an atomic client explicitly built for one reserved topic
      // hashes that topic's contract, not an empty one.
      source: renderClientModule(name, topicDocument, methodName, true),
    };
  });

  if (clientNames.length > 0 && options.serviceName !== undefined && options.serviceName.trim() !== '') {
    const serviceName = toIdentifierSegment(options.serviceName);
    files.push({
      fileName: namespacedFileName(options.namespace, `${serviceName}ClientsRegistration.ts`),
      source: renderAggregateRegistration(serviceName, clientNames),
    });
  }

  return files;
}

function renderAggregateRegistration(serviceName: string, clientNames: readonly string[]): string {
  const lines = [
    '// <auto-generated>',
    `//   Generated by @benzenejs/codegen-client - registers every generated ${serviceName} topic client.`,
    '// </auto-generated>',
    "import { IBenzeneServiceContainer } from '@benzenejs/abstractions';",
    ...clientNames.map((name) => `import { add${name}ServiceClient } from './${name}/${name}ServiceClient';`),
    '',
    `/** Registers every generated ${serviceName} topic client. */`,
    `export function add${serviceName}Clients(container: IBenzeneServiceContainer): IBenzeneServiceContainer {`,
    ...clientNames.map((name) => `  add${name}ServiceClient(container);`),
    '  return container;',
    '}',
  ];
  return `${lines.join('\n')}\n`;
}
