/**
 * Port of Benzene.CodeGen.Client.MessageClientSdkBuilder, retargeted to the mesh ServiceDescriptor and
 * TypeScript. Given a service's descriptor (docs/specification/mesh.md §2 - the same JSON a C#, Go, or
 * TypeScript service emits at its reserved `mesh` topic / `/benzene/descriptor`), it generates a fully
 * typed TypeScript client: a payload interface per topic request/response (from the §2.1 schemas) and a
 * `<Service>ServiceClient` class + `I<Service>ServiceClient` interface with one method per topic that
 * calls `IBenzeneMessageSender.sendAsync`.
 *
 * This is the JSON-Schema-driven realization of Benzene's codegen (see README): the .NET generator
 * derives client types by reflecting over CLR types; deriving them from the wire JSON schemas instead
 * is what makes the client genuinely cross-language - it is generated from the contract, never from the
 * producing runtime's type system.
 */
import { MeshServiceDescriptor } from '@benzenejs/mesh-wire';
import { asJsonSchema } from './JsonSchema';
import { camelCase, toIdentifierSegment } from './NameFormatter';
import { IMethodName, TopicReversedMethodName } from './TopicMethodName';
import { resolvePayloadType } from './TypeScriptPayloadBuilder';

export interface BenzeneClientOptions {
  /** Overrides the client/interface base name (default: the descriptor's `service`, as an identifier). */
  serviceName?: string;
  /** The topic -> method-base strategy (default `TopicReversedMethodName`, e.g. `order:create` -> `createOrder`). */
  methodName?: IMethodName;
}

export interface GeneratedClient {
  readonly fileName: string;
  readonly source: string;
}

interface TopicBinding {
  topic: string;
  method: string;
  requestType: string;
  responseType: string;
}

/** Generates the client source + its file name for a descriptor. */
export function buildBenzeneClient(
  descriptor: MeshServiceDescriptor,
  options: BenzeneClientOptions = {},
): GeneratedClient {
  const serviceName = options.serviceName ?? toIdentifierSegment(descriptor.service);
  const methodName = options.methodName ?? new TopicReversedMethodName();

  const declarations: string[] = [];
  const seenDeclarations = new Set<string>();
  const bindings: TopicBinding[] = [];

  for (const topic of descriptor.topics) {
    const base = methodName.create(topic.id);

    const request = resolvePayloadType(`${base}Request`, asJsonSchema(topic.requestSchema));
    const response = resolvePayloadType(`${base}Response`, asJsonSchema(topic.responseSchema));

    for (const declaration of [request.declaration, response.declaration]) {
      if (declaration !== undefined && !seenDeclarations.has(declaration)) {
        seenDeclarations.add(declaration);
        declarations.push(declaration);
      }
    }

    bindings.push({
      topic: topic.id,
      method: `${camelCase(base)}Async`,
      requestType: request.type,
      responseType: response.type,
    });
  }

  return {
    fileName: `${serviceName}ServiceClient.ts`,
    source: renderModule(serviceName, declarations, bindings),
  };
}

/** Generates just the client source string. */
export function generateBenzeneClientSource(
  descriptor: MeshServiceDescriptor,
  options: BenzeneClientOptions = {},
): string {
  return buildBenzeneClient(descriptor, options).source;
}

function renderModule(serviceName: string, declarations: string[], bindings: TopicBinding[]): string {
  const interfaceName = `I${serviceName}ServiceClient`;
  const className = `${serviceName}ServiceClient`;

  const blocks: string[] = [];

  blocks.push(
    [
      '// <auto-generated>',
      `//   Generated by @benzenejs/codegen-client from the ${serviceName} service's mesh ServiceDescriptor`,
      '//   (docs/specification/mesh.md §2). Do not edit by hand; regenerate from the descriptor.',
      '// </auto-generated>',
      "import { IBenzeneResultOf } from '@benzenejs/abstractions';",
      "import { IBenzeneMessageSender } from '@benzenejs/clients';",
    ].join('\n'),
  );

  blocks.push(...declarations);

  const interfaceLines = [`export interface ${interfaceName} {`];
  for (const binding of bindings) {
    interfaceLines.push(`  ${methodSignature(binding)};`);
  }
  interfaceLines.push('}');
  blocks.push(interfaceLines.join('\n'));

  const classLines = [
    `export class ${className} implements ${interfaceName} {`,
    '  constructor(private readonly sender: IBenzeneMessageSender) {}',
  ];
  for (const binding of bindings) {
    classLines.push('');
    classLines.push(`  ${methodSignature(binding)} {`);
    classLines.push(
      `    return this.sender.sendAsync<${binding.requestType}, ${binding.responseType}>(` +
        `'${binding.topic}', message, headers);`,
    );
    classLines.push('  }');
  }
  classLines.push('}');
  blocks.push(classLines.join('\n'));

  return `${blocks.join('\n\n')}\n`;
}

function methodSignature(binding: TopicBinding): string {
  return (
    `${binding.method}(message: ${binding.requestType}, headers?: Record<string, string>): ` +
    `Promise<IBenzeneResultOf<${binding.responseType}>>`
  );
}
