/**
 * Generates a service-level, topic-include-list-scoped TypeScript client from a Contract Document:
 * a request/response interface per catalogue schema, an `I<Service>ServiceClient` interface, a
 * `<Service>ServiceClient` class whose methods call `IBenzeneMessageSender.sendAsync`, an exported
 * `<Service>ServiceClientRequiredTopics` constant, and an `add<Service>ServiceClient` DI registration
 * function. Port of `Benzene.CodeGen.Client.MessageClientSdkBuilder`, retargeted from OpenAPI-C# to
 * OpenAPI-TypeScript (the Contract Document counterpart of the existing mesh-descriptor-driven
 * `BenzeneClientBuilder.ts` - see that file's header for the JSON-Schema-pivoted "first" input path;
 * this is the "second, additional" one, contract-document.md's, per the README Porting-conventions
 * table).
 *
 * Divergence from `Benzene.Abstractions.DI.IBenzeneServiceContainer`'s C# `AddScoped<TService,
 * TImplementation>()` reflection-based constructor injection: TypeScript erases types, so the
 * generated class declares a static `inject` array (this repo's established DI convention - see
 * `ServiceToken.ts`'s `InjectableConstructor`) instead of relying on reflection.
 */
import { ClientSdkOptions } from './ClientSdkOptions';
import { computeContractHash } from './ContractHash';
import { ContractDocument, ContractRequestResponse } from './ContractDocument';
import { camelCase, toIdentifierSegment } from './NameFormatter';
import { buildTypeDeclarations } from './OpenApiPayloadBuilder';
import { typeExpression } from './OpenApiTypeName';
import { IMethodName, TopicReversedMethodName } from './TopicMethodName';
import { applyTopicScope } from './TopicScope';

export interface GeneratedClient {
  readonly fileName: string;
  readonly source: string;
}

export interface MessageClientSdkOptions extends ClientSdkOptions {
  /** The topic -> method-base strategy (default `TopicReversedMethodName`, e.g. `order:create` -> `createOrderAsync`). */
  methodName?: IMethodName;
}

/** Generates the service-level client source + its file name for `document`, scoped by `options`. */
export function buildMessageClientSdk(document: ContractDocument, options: MessageClientSdkOptions): GeneratedClient {
  if (options.serviceName === undefined || options.serviceName.trim() === '') {
    throw new Error('options.serviceName is required for buildMessageClientSdk');
  }

  const serviceName = toIdentifierSegment(options.serviceName);
  const scoped = applyTopicScope(document, options);
  const methodName = options.methodName ?? new TopicReversedMethodName();

  return {
    // options.namespace is used exactly - as the output directory a service-level client's file lands
    // under, no magic suffix (contract-document.md §5.5 leaves file layout to each port's idiom; TS
    // modules have no `namespace` keyword to wrap output in, so the C# "namespace" concept maps onto
    // the generated file's own path instead).
    fileName: namespacedFileName(options.namespace, `${serviceName}ServiceClient.ts`),
    // A service-level client (§5.2's include-list projection, or the domain-only default) is never
    // topic-scoped for hash purposes (contract-document.md §6.2) - only a single-topic atomic client is.
    source: renderClientModule(serviceName, scoped, methodName, false),
  };
}

/** Generates just the client source string. */
export function generateMessageClientSource(document: ContractDocument, options: MessageClientSdkOptions): string {
  return buildMessageClientSdk(document, options).source;
}

/** Joins `namespace` and `relativePath` as a directory prefix, tolerating an empty/undefined namespace. */
export function namespacedFileName(namespace: string | undefined, relativePath: string): string {
  return namespace !== undefined && namespace.trim() !== '' ? `${namespace}/${relativePath}` : relativePath;
}

interface TopicBinding {
  topic: string;
  method: string;
  requestType: string;
  responseType: string;
}

/**
 * Renders one client module's full source: type declarations, interface, class, `RequiredTopics`,
 * and DI registration. Shared by `buildMessageClientSdk` and `AtomicClientSdkBuilder.ts` (which calls
 * this once per topic against that topic's already-projected, topic-scoped document).
 */
export function renderClientModule(
  serviceName: string,
  document: ContractDocument,
  methodName: IMethodName,
  isTopicScopedForHash: boolean,
): string {
  const interfaceName = `I${serviceName}ServiceClient`;
  const className = `${serviceName}ServiceClient`;
  const contractHash = computeContractHash(document, { topicScoped: isTopicScopedForHash });

  const declarations = buildTypeDeclarations(document.components.schemas);
  const bindings = document.requests.map((request) => toBinding(request, methodName));

  const blocks: string[] = [];

  blocks.push(
    [
      '// <auto-generated>',
      `//   Generated by @benzenejs/codegen-client from the ${serviceName} service's Contract Document`,
      '//   (docs/specification/contract-document.md). Do not edit by hand; regenerate from the .spec.json.',
      '// </auto-generated>',
      "import { IBenzeneResultOf, IBenzeneServiceContainer, ServiceToken, serviceToken } from '@benzenejs/abstractions';",
      "import { IBenzeneMessageSender } from '@benzenejs/clients';",
    ].join('\n'),
  );

  blocks.push(...declarations);
  blocks.push(renderInterface(interfaceName, bindings));
  blocks.push(renderClass(className, interfaceName, contractHash, bindings));
  blocks.push(renderRequiredTopics(serviceName, document.requests));
  blocks.push(renderRegistration(serviceName, interfaceName, className));

  return `${blocks.join('\n\n')}\n`;
}

function toBinding(request: ContractRequestResponse, methodName: IMethodName): TopicBinding {
  const base = methodName.create(request.topic);
  return {
    topic: request.topic,
    method: `${camelCase(base)}Async`,
    requestType: typeExpression(request.request),
    responseType: typeExpression(request.response),
  };
}

function renderInterface(interfaceName: string, bindings: TopicBinding[]): string {
  const lines = [`export interface ${interfaceName} {`];
  for (const binding of bindings) {
    lines.push(`  ${methodSignature(binding)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function renderClass(className: string, interfaceName: string, contractHash: string, bindings: TopicBinding[]): string {
  const lines = [
    `export class ${className} implements ${interfaceName} {`,
    `  static readonly inject = [IBenzeneMessageSender] as const;`,
    '',
    '  private readonly sender: IBenzeneMessageSender;',
    '',
    '  constructor(sender: IBenzeneMessageSender) {',
    '    this.sender = sender;',
    '  }',
    '',
    `  /** The Contract Document's contractHash (docs/specification/contract-document.md §6) this client was generated from. */`,
    `  static readonly contractHash = '${contractHash}';`,
  ];
  for (const binding of bindings) {
    lines.push('');
    lines.push(`  ${methodSignature(binding)} {`);
    lines.push(
      `    return this.sender.sendAsync<${binding.requestType}, ${binding.responseType}>(` +
        `'${binding.topic}', message, headers);`,
    );
    lines.push('  }');
  }
  lines.push('}');
  return lines.join('\n');
}

function methodSignature(binding: TopicBinding): string {
  return (
    `${binding.method}(message: ${binding.requestType}, headers?: Record<string, string>): ` +
    `Promise<IBenzeneResultOf<${binding.responseType}>>`
  );
}

// Reflected over by an outbound-routing start-up check (mirroring Benzene.Clients' C#
// ValidateOutboundRouting()) - exactly the topics this client has methods for. Benzene's own reserved
// endpoints (benzene:*) are framework plumbing, excluded by TopicScope like any other reserved topic
// unless explicitly asked for; naming one here would demand an outbound route the consumer never
// asked for.
function renderRequiredTopics(serviceName: string, requests: ContractRequestResponse[]): string {
  const topics = requests.map((request) => `'${request.topic}'`).join(', ');
  return `export const ${serviceName}ServiceClientRequiredTopics: readonly string[] = [${topics}];`;
}

function renderRegistration(serviceName: string, interfaceName: string, className: string): string {
  const lines = [
    `export const ${interfaceName}: ServiceToken<${interfaceName}> = serviceToken<${interfaceName}>('${interfaceName}');`,
    '',
    `/** Registers ${className} as ${interfaceName}. */`,
    `export function add${serviceName}ServiceClient(container: IBenzeneServiceContainer): IBenzeneServiceContainer {`,
    `  return container.addScoped(${interfaceName}, ${className});`,
    '}',
  ];
  return lines.join('\n');
}
